name: Deploy dev
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 24 }
      - run: npm ci && npm run build
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_TEST }}
          username: ${{ secrets.FTP_USERNAME_TEST }}
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          server-dir: htdocs/
          exclude: |
            **/.git*/**
            **/node_modules/**
            docs/*
            vendor/**
            storage/**
            tests/**
            .env